"""add user auth fields and unique profile user_id

Revision ID: 77dfff7161d0
Revises: 2c4aeebd0fad
Create Date: 2026-09-27 10:21:06.225971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77dfff7161d0'
down_revision: Union[str, Sequence[str], None] = '2c4aeebd0fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_patients_user_id', 'patients', ['user_id'])
    op.create_unique_constraint('uq_providers_user_id', 'providers', ['user_id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_constraint('uq_providers_user_id', 'providers', type_='unique')
    op.drop_constraint('uq_patients_user_id', 'patients', type_='unique')
    # ### end Alembic commands ###
